# Eval3D strategy tuned for the rigid objects node.
_import_: ./eval3d.yaml
strategy_cfg:
  config:
    densify_end_iter: 30000
    densify_grad_thr: 0.001
    densify_scale2d_stop_iter: 40000
    density_reset_end_iter: 30000
    prune_scale3d: 0.1
