_fn_: xsim.modeling.nodes.gaussian.GaussianContainer.create
nodes:
  - _import_:
      - ./static.yaml
      - ./features/raw.yaml
      - ./mixins/lidar_density.yaml
      - ./regularization/sharp_shape.yaml
      - ./regularization/lidar_density.yaml
      - ./strategy/eval3d_static.yaml
  - _import_:
      - ./rigid.yaml
      - ./features/raw.yaml
      - ./mixins/lidar_density.yaml
      - ./regularization/sharp_shape.yaml
      - ./regularization/lidar_density.yaml
      - ./strategy/eval3d_rigid.yaml
  - _import_:
      - ./deformable.yaml
      - ./features/raw.yaml
      - ./mixins/lidar_density.yaml
      - ./regularization/sharp_shape.yaml
      - ./regularization/lidar_density.yaml
      - ./strategy/eval3d_deformable.yaml
  - _import_:
      - ./smpl_raw.yaml
      - ./mixins/lidar_density.yaml
